### ISSUE TITLE
Access to the machine console with an existing private key also works without a valid token

### ISSUE THREAD

**Issue by y16144** [metal-stack/metal-console#29]
/usr/bin/ssh -i privatekey f08150815-4911-4242-4911-3cecef6d5ebc@api.fits.cloud -p 5222 -o StrictHostKeyChecking=No

Connecting to console of "f08150815-4911-4242-4911-3cecef6d5ebc" ...
Exit with ~.
[SOL Session operational.  Use ~? for help]

**Comment by majst01** [comment]
Gardener rotates ssh-keypairs since https://github.com/gardener/gardener/pull/4224, i really would prefer this.

**Comment by Gerrit91** [comment]
Idea during planning: 

- Create temporary SSH key per console session, store it in the machine entity
- metal-console then checks presented public key with the stored private key
- Removes the stored private key immediately after the session was established

**Comment by majst01** [comment]
SSH Key rotation is now in place, could we close this issue now ?

**Comment by Gerrit91** [comment]
Please re-open if this is not solved yet.
